### ISSUE TITLE
Change gemspec to allow rails 5.1 betas

### ISSUE THREAD

**Issue by clairity** [hult/acts_as_having_string_id#13]
Currently `acts_as_having_string_id.gemspec` specifies
```
s.add_dependency "rails", "~> 5.0.0", ">= 5.0.0.1"
```
any chance this dependency could be changed to something like `"~> 5.0", ">= 5.0.0.1"` so that we could use acts_as_having_string_id with the 5.1.0.beta releases? I'm getting a bundler dependency resolution error when i try to update to rails 5.1.0.beta1.

**Comment by hult** [comment]
Thanks for reporting! Yeah, it should definitely be something like that (provided it still works of course :). Feel free to submit a pull request, or I'll fix it tomorrow.

**Comment by clairity** [comment]
Ok, I forked and made the changes locally and it seemed to work for me. Any instructions on testing before I submit a pull request?

**Comment by hult** [comment]
As I see it, the dependency restrictions were incorrectly set too tight from the beginning, so I don't think testing beyond the automatic tests is necessary (and if you're on a Rails beta, you should probably be prepared for things not working perfectly anyways). Submit the PR and if it works for me, I'll merge it. Thanks a lot for your help!

**Comment by hult** [comment]
What's even the rationale for having an upper bound on versions anyway? I think it'd be better allowing people to install the lib on newer versions, and then report any bugs they bump in to?

**Comment by clairity** [comment]
submitted PR: #14 

not sure about upper bounds other than making sure that testing gets implemented and done before letting it out in the wild. i think it's up to you. 🙂
